from __future__ import annotations

from pathlib import Path
from typing import Any

from .catalog import Catalog, load_catalog
from .io import load_record, load_yaml, locate_overlay, principal_id, record_files


GENERATED_NOTICE = "<!-- Generated by agentic-engineering. Do not edit directly. -->"


def _capabilities(program: dict[str, Any]) -> dict[str, dict[str, Any]]:
    payload = program.get("program") if isinstance(program.get("program"), dict) else program
    raw = payload.get("capabilities", {})
    if isinstance(raw, dict):
        return {
            str(key): (value if isinstance(value, dict) else {"status": str(value)})
            for key, value in raw.items()
        }
    if isinstance(raw, list):
        result: dict[str, dict[str, Any]] = {}
        for item in raw:
            if isinstance(item, str):
                result[item] = {"disposition": "active"}
            elif isinstance(item, dict) and isinstance(item.get("id"), str):
                result[item["id"]] = item
        return result
    return {}


def _project_title(program: dict[str, Any]) -> str:
    project = program.get("program", program)
    if not isinstance(project, dict):
        return "Project"
    return str(project.get("name") or project.get("id") or "Project")


def _accountability(assignment: dict[str, Any]) -> str:
    for key in ("accountable", "owner", "reviewer"):
        value = principal_id(assignment.get(key))
        if value:
            return value
    return "—"


def _principals(value: Any) -> str:
    if isinstance(value, str):
        return value
    if isinstance(value, list):
        items = [item for item in value if isinstance(item, str)]
        return ", ".join(items) if items else "—"
    return "—"


def _operating_model(program: dict[str, Any], control_root: str) -> str:
    project = program.get("program", {}) if isinstance(program.get("program"), dict) else program
    profile = project.get("profile", {}) if isinstance(project.get("profile"), dict) else {}
    source = (
        project.get("source_of_truth", {})
        if isinstance(project.get("source_of_truth"), dict)
        else {}
    )
    tailoring = project.get("tailoring", {}) if isinstance(project.get("tailoring"), dict) else {}
    framework_lock = (
        project.get("framework_lock", {})
        if isinstance(project.get("framework_lock"), dict)
        else {}
    )
    gate = project.get("current_gate", "—")
    lines = [
        GENERATED_NOTICE,
        "",
        f"# {_project_title(program)} Operating Model",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| Project ID | {project.get('id', '—')} |",
        f"| Product type | {profile.get('product_type', '—')} |",
        f"| Phase | {profile.get('lifecycle_phase', '—')} |",
        f"| Current gate | {gate} |",
        f"| Authoritative source | {source.get('path', '—')} |",
        f"| Source version | {source.get('declared_version', '—')} |",
        f"| Framework version | {program.get('framework_version', '—')} |",
        f"| Framework catalog lock | {str(framework_lock.get('catalog_sha256', '—'))[:16]}… |",
        f"| Tailoring | {tailoring.get('status', 'not recorded')} |",
        "",
        f"The manifest and records under `{control_root}` are authoritative. Generated views are disposable.",
        "",
    ]
    return "\n".join(lines)


def _role_coverage(program: dict[str, Any], catalog: Catalog) -> str:
    assignments = _capabilities(program)
    capability_ids = sorted(set(catalog.capabilities) | set(assignments))
    lines = [
        GENERATED_NOTICE,
        "",
        "# Capability Coverage",
        "",
        "| Capability | Status | Owner | Executors | Reviewers | Activation or Reason |",
        "|---|---|---|---|---|---|",
    ]
    for capability_id in capability_ids:
        assignment = assignments.get(capability_id, {})
        status = assignment.get("disposition", assignment.get("status", "unassigned"))
        detail = (
            assignment.get("reason")
            or assignment.get("rationale")
            or assignment.get("reconsider_when")
            or assignment.get("activate_at_gate")
            or assignment.get("activate_when")
            or assignment.get("activation")
            or "—"
        )
        if isinstance(detail, list):
            detail = ", ".join(str(item) for item in detail)
        lines.append(
            f"| `{capability_id}` | {status} | {_accountability(assignment)} | "
            f"{_principals(assignment.get('executors'))} | "
            f"{_principals(assignment.get('reviewers'))} | {detail} |"
        )
    lines.append("")
    return "\n".join(lines)


def _active_work(overlay: Path) -> str:
    rows: list[tuple[str, str, str, str, str]] = []
    for kind in ("work", "packets"):
        for path in record_files(overlay, kind):
            try:
                record, _ = load_record(path)
            except (OSError, ValueError):
                continue
            state = record.get("state", record.get("status", "—"))
            if isinstance(state, dict):
                state = state.get("current", "—")
            if state in {"accepted", "closed", "released", "rejected", "kill"}:
                continue
            risk = record.get("risk_tier", record.get("risk", "—"))
            if isinstance(risk, dict):
                risk = risk.get("effective_tier", risk.get("declared_tier", "—"))
            rows.append(
                (
                    str(record.get("id", path.stem)),
                    str(record.get("workflow", record.get("route", "—"))),
                    str(state),
                    str(risk),
                    str(path.relative_to(overlay)),
                )
            )
    lines = [
        GENERATED_NOTICE,
        "",
        "# Active Work",
        "",
        "| ID | Workflow | State | Risk | Record |",
        "|---|---|---|---|---|",
    ]
    for row in sorted(rows):
        lines.append(f"| `{row[0]}` | {row[1]} | {row[2]} | {row[3]} | `{row[4]}` |")
    if not rows:
        lines.append("| — | — | — | — | No active work records |")
    lines.append("")
    return "\n".join(lines)


def _agents_guidance(program: dict[str, Any], manifest_ref: str) -> str:
    project = program.get("program", {}) if isinstance(program.get("program"), dict) else program
    profile = project.get("profile", {}) if isinstance(project.get("profile"), dict) else {}
    source = (
        project.get("source_of_truth", {})
        if isinstance(project.get("source_of_truth"), dict)
        else {}
    )
    gate = project.get("current_gate", "not declared")
    lines = [
            GENERATED_NOTICE,
            "",
            f"# Agent Guidance: {_project_title(program)}",
            "",
            f"Authoritative program source: `{source.get('path', 'not configured')}` "
            f"(version `{source.get('declared_version', 'not configured')}`).",
            f"Current phase/gate: `{profile.get('lifecycle_phase', 'not configured')}` / `{gate}`.",
            "",
            "## Required operating rules",
            "",
            f"1. Read `{manifest_ref}` before substantive work.",
            "2. Use canonical YAML records; Markdown under `generated/` is disposable.",
            "3. Route work by workflow and consequence facts before execution.",
            "4. Do not exceed either the work packet permissions or the actor ceiling.",
            "5. Cite typed, subject-bound receipts for manual guards and elevated actions.",
            "6. Satisfy producer/validator separation required by the assurance level.",
            "7. Do not make claims stronger than passing linked evidence authorizes.",
            "8. Stop when scope, permission class, source revision, or risk tier changes.",
            "",
            "## Declared actors",
            "",
            "| Actor | Kind | Permission ceiling | Capabilities |",
            "|---|---|---|---|",
        ]
    for actor in project.get("actors", []):
        if not isinstance(actor, dict):
            continue
        capabilities = _principals(actor.get("capabilities"))
        lines.append(
            f"| `{actor.get('id', '—')}` | {actor.get('kind', '—')} | "
            f"{actor.get('permission_ceiling', '—')} | {capabilities} |"
        )
    lines.extend(
        [
            "",
            "## Local control commands",
            "",
            "```bash",
            "agentic validate . --strict",
            "agentic route <WORK-ID> --root .",
            "agentic render .",
            "```",
            "",
            "Generated guidance is a view. Update the manifest or records, then render again.",
            "",
        ]
    )
    return "\n".join(lines)


def expected_rendered(
    root: Path, *, catalog: Catalog | None = None, framework: Path | None = None
) -> tuple[Path, dict[str, str]]:
    _, overlay = locate_overlay(root)
    program = load_yaml(overlay / "program.yaml")
    catalog = catalog or load_catalog(framework)
    manifest_ref = ".agentic/program.yaml" if overlay.name == ".agentic" else "program.yaml"
    control_root = ".agentic/" if overlay.name == ".agentic" else "the project-instance root"
    return overlay / "generated", {
        "operating-model.md": _operating_model(program, control_root),
        "role-coverage.md": _role_coverage(program, catalog),
        "active-work.md": _active_work(overlay),
        "AGENTS.md": _agents_guidance(program, manifest_ref),
    }


def render_project(
    root: Path, *, catalog: Catalog | None = None, framework: Path | None = None
) -> list[Path]:
    output_root, rendered = expected_rendered(root, catalog=catalog, framework=framework)
    output_root.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for name, content in rendered.items():
        path = output_root / name
        path.write_text(content.rstrip() + "\n", encoding="utf-8")
        written.append(path)
    return written
